#!/usr/bin/env bash
# Display numbers from 1 to 100
# Display FizzBuzz when the number is a multiple of 3 and 15
# Display Fizz when the number is multiple of 9
# Display Buzz when the number is a multiple of 5
# Otherwise Display number
# In list format

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
