#!/usr/bin/env bash
# Loops from 0 to 10
# Display bad for the 4th loop
# Display good luck for the 8th loop
# Display Best School for the other iteration

count=0

while [ $count -lt 10 ]
do 
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
