#!/usr/bin/env bash
# Display number from 1 to 20
# display 4 and bad luck from china on 4th loops
# Display 9 and bad luck from japan on 9th loops
# Display 17 and bad luck from Italy on 17th loops

count=1
while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from china";;
		"9") echo "bad luck from japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done
