#!/usr/bin/env bash
# Write a script that configure a ubuntu server with below requirements:
# localhost resolve to 127.0.0.2
# facebook.com resolve to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
